### ISSUE TITLE
Are you free-riders too?

### ISSUE THREAD

**Issue by nikaro** [getsentry/fsl.software#15]
Do you sponsors all the actual open-source libs you use in your FSL softwares? Or are you free-riders yourselves?

**Comment by RhysSullivan** [comment]
@nikaro a simple Google search shows you Sentry sponsored $500,000 this year to OSS https://blog.sentry.io/we-just-gave-500-000-dollars-to-open-source-maintainers/

In the blog you'll also see all the previous years they've done that

**Comment by chadwhitacre** [comment]
Thanks @RhysSullivan. Seeing your 👍 @nikaro, closing.

**Comment by chadwhitacre** [comment]
For the record, not only do we sponsor our own dependencies, we are actively recruiting other companies to follow suit through the [FOSS Funders working group](https://fossfunders.com/).
