### ISSUE TITLE
Patents

### ISSUE THREAD

**Issue by mkg20001** [getsentry/fsl.software#16]
Hi,
the Apache2 License includes a paragraph that prevents a contributor from contributing code that infringes upon contributor's patent and then suing the people using the software.

Maybe it's already covered by the FSL license, but otherwise that would be an important addition

Here's the excerpt from the apache2 license

>3. Grant of Patent License. Subject to the terms and conditions of this License, each Contributor hereby grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by such Contributor that are necessarily infringed by their Contribution(s) alone or by combination of their Contribution(s) with the Work to which such Contribution(s) was submitted. If You institute patent litigation against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that the Work or a Contribution incorporated within the Work constitutes direct or contributory patent infringement, then any patent licenses granted to You under this License for that Work shall terminate as of the date such litigation is filed.

**Comment by chadwhitacre** [comment]
> Maybe it's already covered by the FSL license

Did you [read it](https://github.com/getsentry/fsl.software/blob/main/FSL-1.0-Apache-2.0.template.md#patents)? 🤔

**Comment by mkg20001** [comment]
>To the extent your use for a Permitted Purpose would necessarily infringe our patents, the license grant above includes a license under our patents.

does that include the contributor giving a license for their patents? or just the licensor (or is we different then ours)

**Comment by chadwhitacre** [comment]
cc: @gavin-zee

**Comment by gavin-zee** [comment]
FSL addresses patent grants from the licensor (not contributors). The licensor may or may not receive patent rights from a contributor depending on what form of contribution license the licensor has implemented.

**Comment by chadwhitacre** [comment]
Considering this one answered.
