### ISSUE TITLE
"in a way that exposes the APIs of the Software" is an ambiguous example of competing use

### ISSUE THREAD

**Issue by benvinegar** [getsentry/fsl.software#18]
Example of how this is ambiguous:

If, as part of typical operation of the FSL-licensed software, the user must expose the software's API to receive inbound HTTP requests from an integration / 3rd party service, that sounds like a competing use per the license text.

**Comment by chadwhitacre** [comment]
[Related from YouTube](https://www.youtube.com/watch?v=UB9fo7pnDzY&lc=UgyyKymT5f-tSwL8SCR4AaABAg):

> So exposing any type of API makes you ineligible for FSL use?

**Comment by chadwhitacre** [comment]
Heads up we've removed the reference to APIs on #32. Hope this suffices.

**Comment by chadwhitacre** [comment]
Following up to ask specifically ... @benvinegar Are you good with the approach on #32, removing the reference to APIs entirely?

**Comment by benvinegar** [comment]
AFAICT the approach is "entirely removed that line", so, I think so.

**Comment by chadwhitacre** [comment]
Okay, gonna call this good with #32. 👍
