### ISSUE TITLE
Support OSI's research on DOSP

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/fsl.software#3]
OSI is [conducting](https://code.librehq.com/ots/dosp-research) "[r]esearch on delayed open source publication (DOSP): the practice of publishing a software release under a proprietary license, then later publishing that release's source code under an open source license." Sentry is a sponsor of this research, and we welcome others to join us. The expectation is that we'll end up with a whitepaper later this year.

**Comment by chadwhitacre** [comment]
The feeling at Sentry is that releasing under an OSI license eventually demonstrates a general commitment to Open Source in a way that BUSL w/o the conversion does not. Its less about customers and more about other devs being able to learn from and reuse our code over time.

@kfogel Does your research address motivations on the part of licensors/authors? How about uptake patterns on the part of the community post-delayed-release?

**Comment by chadwhitacre** [comment]
The paper is done! 💃

I haven't seen it announced publicly yet though ...

**Comment by chadwhitacre** [comment]
[Here it is in LaTeX](https://code.librehq.com/ots/dosp-research/-/blob/3efcf5aa69e518c6302b240a86809935aa507ab8/dosp-survey.ltx). 😁

**Comment by kfogel** [comment]
Hi, @chadwhitacre!  Sorry I didn't see the notification from when you nick-flagged me above exactly a month ago (GitHub notifications, even when they arrive by email, don't have a lot of the metadata that I normally use to route my email, so I generally miss them unless I was expecting them and [set things up in advance](https://www.gnu.org/software/emacs/manual/html_node/gnus/Fancy-Mail-Splitting.html) to route them correctly).

The paper raises the question of contributor motivations, and contribution trends more generally, as an area for further research.  This paper is really just a survey, though: it looks over the landscape or patterns, and tries to identify questions to ask next.  We agree with you and @djc that that's one of the most important questions.

**Comment by kfogel** [comment]
We're working with OSI to produce a nicely-formatted version with Pleasing Design Elements, by the way, so although the content of the paper is complete (modulo any last-minute bug reports), it's not been officially announced yet.  That'll happen when the glossy copy is ready.

**Comment by chadwhitacre** [comment]
Announcement is tomorrow! 🙌

**Comment by kfogel** [comment]
Aaaaaaand... it's out!

https://opensource.org/delayed-open-source-publication/

https://blog.opensource.org/a-historic-view-of-the-practice-to-delay-releasing-open-source-software-osis-report/
