### ISSUE TITLE
Branding for non-compete licenses

### ISSUE THREAD

**Issue by dcramer** [getsentry/fsl.software#31]
This topic continues forever.

We need a way to talk about licenses like FSL, BUSL, and arguably even things like Elastic. They _cannot_ be called Open Source (and we should make that clear in our faq/whatever). They _are not_ Closed Source. They are _different than_ source-available.

This is a marketing exercise at the end of the day, so I'm not looking for academic opinions here. This is about what public perception is and needs to be. We need a term that aligns with the freedoms we're granted, but does not diminish the value of Open Source.

**Comment by ljharb** [comment]
what is COSS?

**Comment by ljharb** [comment]
That makes sense to me, modulo the likely extreme unfamiliarity with that term.

**Comment by dcramer** [comment]
> That makes sense to me, modulo the likely extreme unfamiliarity with that term.

IMO, because these are not the same old closed source, source-available, etc licenses of yesteryear, we need a way to talk about it that does not have predjudice. Same problem as trying to suggest they're Open Source. All those terms have historical meaning that arguably should not change.
