### ISSUE TITLE
Create a List of Business Models

### ISSUE THREAD

**Issue by WisTex** [getsentry/fsl.software#34]
Re: https://softwarecommons.com

Are the categories supposed to be license types or business models?

Instead of trying to combine both into one classification list, perhaps we classify software using both.

Examples:

Core Licensing: Open Source - Copyleft
Addon Licensing: Proprietary
Business Model: Freemium (e.g. Open Core / Premium Addons)

Core Licensing: Open Source - Copyleft
Dual Licensing: Available
Addon Licensing: Varies
Business Model: Support Services, Customization & Development Services

Core Licensing: Open Source - Permissive
Addon Licensing: Open Source - Permissive
Third-Party Addon Licensing: Varies
Business Model: Donations & Contributions

Licensing: Public Domain
Business Model: Gift to Public (i.e. does not accept donations)

Mix and match licensing and business model as appropriate.

**Comment by chadwhitacre** [comment]
@dcramer I think this might be similar to what you were talking about with distribution models, etc.?

**Comment by dcramer** [comment]
Yes, separating the decision points on business, distribution, contribution models

**Comment by chadwhitacre** [comment]
> yes we should articulate the ecosystem, the decision points, examples of those decision points, etc
> basically it needs to be trustable resource

**Comment by chadwhitacre** [comment]
I'm folding this into #30.
