### ISSUE TITLE
Can I sell software licensed under this license?

### ISSUE THREAD

**Issue by djkato** [getsentry/fsl.software#35]
Hello, I'm new to licensing and from the many permissive licenses this one caught my eye. 

If I use this license and add something like *"To use commercially, send me 10€ on kofi and then the software will be automatically under MIT License for you only,"* or something like that. 

I want my code to be free for non-commercial use, and have a small reward for when someone makes money with it. But I don't want to make an e-shop and actually distribute new licenses and all that hassle, just something to make sure I can get *something* from my work. 

Can I also alter the timespan in which software becomes MIT? 2 years doesn't sound like much.

Is this license a good option for that?

Sorry if this question is not well worded, but this is a complicated topic for me.

**Comment by chadwhitacre** [comment]
Thanks for the questions @djkato. It seems like the FSL is not a good option for you, no. If you change the FSL in the ways you suggest, it will be a different license, not the FSL anymore. If licensing is a complicated topic for you, your best bet is to hire a lawyer. Short of that, maybe one of the [PolyForm licenses](https://polyformproject.org/licenses/) would suit you better?

Good luck!
