### ISSUE TITLE
Implications of usage restriction on patch releases

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/fsl.software#43]
Reticketing from @karsten-klein at https://github.com/spdx/license-list-XML/issues/2458#issuecomment-2079700518:

> Does it also mean that I cannot commercially use a new security patch on a two year old library, before the patch itself is two years old?

**Comment by chadwhitacre** [comment]
Silence is assent. Closing as answered.

**Comment by karsten-klein** [comment]
Yet an argument to hesitate from using FSL licensed software in a commercial context, due to complexity of license management.

**Comment by chadwhitacre** [comment]
An argument that [has not swayed 10,000+ companies](https://openpath.chadwhitacre.com/2024/widespread-use-of-a-fair-source-product/).
