### ISSUE TITLE
Submit to OSI to become an approved license

### ISSUE THREAD

**Issue by pavanpodila** [getsentry/fsl.software#48]
Please submit FSL to the OSI so they can mark it as an approved license: https://opensource.org/licenses

This helps in resolving it as a "known" license, on package registries like pub.dev. In the [Vyuh Framework](https://vyuh.tech), which comprises of several packages, we have adopted FSL but it is not yet recognized on pub.dev as a known license.

See here where it still says: "unknown license": https://pub.dev/packages/vyuh_core

Would be great to get it ack'ed by OSI.

**Comment by astrojuanlu** [comment]
FSL doesn't aim to be a OSI-approved license, AFAIU:

![image](https://github.com/getsentry/fsl.software/assets/316517/74f9314c-d0ab-494d-b89e-b75344f3bb31)

**Comment by pavanpodila** [comment]
I think FSL is compliant except for the part where it prevents competition to do similar things for a period of 2 years, beyond which it becomes an OSI approved license (MIT or Apache). This needs to be checked with the OSI folks.

**Comment by MattiSG** [comment]
> FSL is compliant except for the part where

Yes, so it is not compliant 🙂

**Comment by pavanpodila** [comment]
I am no expert on the subject but I do see other restrictive licenses on OSI, so I think it would be good to vet it out with an expert from their side ?

**Comment by MattiSG** [comment]
[Open Source Definition](https://opensource.org/osd):

> The license must not restrict anyone from making use of the program in a specific field of endeavor.

[FSL](https://github.com/getsentry/fsl.software/blob/main/FSL-1.1-MIT.template.md);

> we hereby grant you the right to use, copy, modify, create derivative works, publicly perform, publicly display and redistribute the Software for any Permitted Purpose identified below. […] A Permitted Purpose is any purpose other than a Competing Use

Therefore, FSL restricts everyone from making use of the program in the specific field of endeavor of Competing Use.
It thus does not comply with the Open Source Definition.
It is therefore not eligible to be approved by the OSI.

Voting to close this issue.

**Comment by pavanpodila** [comment]
ok

**Comment by chadwhitacre** [comment]
Thanks, team. See https://github.com/getsentry/fsl.software/issues/21 for related.
