### ISSUE TITLE
FSL-1.1-ISC

### ISSUE THREAD

**Issue by poolpOrg** [getsentry/fsl.software#49]
Hello,

Is it ok to make variations of the FSL that release to other licenses ?

I'm interested to release some software under the FSL but would like the license to be converted to the ISC license, which is functionally equivalent to the simplified BSD and MIT licenses, due to the fact that I come from a software environment where ISC is the norm.

[ISC License](https://en.wikipedia.org/wiki/ISC_license)

Would it be ok to state the software is FSL-1.1-ISC or FSL-1.1-OpenBSD licensed ?

I know I could just make a similar one and name it otherwise but I'd rather make the suggestion here first and see if it's ok :-)

**Comment by chadwhitacre** [comment]
Hi, @poolpOrg. Thanks for chiming in.

> Would it be ok to state the software is FSL-1.1-ISC or FSL-1.1-OpenBSD licensed ?

Binary answer: no. 😞 One of our main goals for FSL is to keep it simple, and that includes not having more change licenses than necessary. We did [consider ISC](https://github.com/getsentry/fsl.software/issues/4#issuecomment-1782760880); here's where we [decided against it](https://github.com/getsentry/fsl.software/issues/4#issuecomment-1796963968):

> BSD and ISC don't really offer anything over MIT, so based on that it seems like Apache 2.0 + MIT will cover like 99%+ of the community we're aiming for.

"I come from a software environment where ISC is the norm." I take it this is OpenBSD, yes? What happens if you use FSL-1.1-MIT? 😬

**Comment by poolpOrg** [comment]
Hello, understood, no worries.

> I take it this is OpenBSD, yes? What happens if you use FSL-1.1-MIT? 😬

It is OpenBSD indeed.

Nothing would happen but since ISC is the preferred license and my existing code is already ISC-licensed, it would have avoided the mess of having some code ISC, some code FSL and some code converted to MIT, it would either be ISC or FSL for newer code, making it easier to communicate on licenses.

Not a big deal, I understand what you're trying to achieve so nevermind.

Thanks for your quick answer,
Gilles

**Comment by chadwhitacre** [comment]
If you do end up forking the FSL and you get some traction with it, I guess we will want to acknowledge your fork on [fair.io/licenses](https://fair.io/licenses/). 🙃

**Comment by poolpOrg** [comment]
Sure thing.

I'm currently weighting options because I would very much like not to fork a license, and certainly won't just to retain ISC over MIT, but another aspect of the FSL is not totally aligned with what we were looking for and so we need to decide if we can live with it or not :-)

**Comment by chadwhitacre** [comment]
Have you explored the alternatives on [fair.io/licenses](https://fair.io/licenses)? You might also investigate https://github.com/fairsource/fair.io/issues/31 in case a PolyForm variant would be a good fit. Good luck! :-)
