### ISSUE TITLE
Question about Permitted Purpose

### ISSUE THREAD

**Issue by ralph-bergmann** [getsentry/fsl.software#55]
I'm developing a software project that I might offer as a paid SaaS, and I'm wondering which license I should use. I like the idea behind the Functional Source License (FSL-1.1-MIT), but I have a question:

```
### Permitted Purpose

2. substitutes for any other product or service we offer using the Software
   that exists as of the date we make the Software available; or
```

Does this mean that anyone can start offering a paid SaaS as long as I don't?

**Comment by gavin-zee** [comment]
@ralph-bergmann no, no one is able to make a commercial offering that substitutes for the software itself (competing use example number 1). Example 2 would be for things like paid support or paid professional services that you might offer.

**Comment by ralph-bergmann** [comment]
ah, understand :-)
